In [1]:
##############################
#Ways Of Creating numpy array#
##############################
###########################
#1st Way :- using np.array#
###########################
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a)
print(b)

[1 2 3]
[5 6 7]


In [3]:
############################
#2nd Way :- using np.arange#
############################

c=np.arange(5,50,5)
print(c)

[ 5 10 15 20 25 30 35 40 45]


In [10]:
##############################
#3rd Way :- using np.linspace#
##############################

d=np.linspace(1,2/3,4)
print(d)

[1.         0.88888889 0.77777778 0.66666667]


In [11]:
#######################
#4th Way :- using list#
#######################

L=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(L)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
########################
#5th Way :- using tuple#
########################

T=(1,2,3,4,5,6,7,8,9,10)
Tarr=np.array(T)
print(Tarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
##########################
#6th Way :- using np.ones#
##########################

e=np.ones((4,5),dtype=np.int16)
print(e)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
###########################
#7th Way :- using np.zeros#
###########################

f=np.zeros((4,5),dtype=np.int16)
print(f)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
##########################
#8th Way :- using np.full#
##########################

g=np.full((4,5),2.3)
print(g)

[[2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3]]


In [20]:
#################################
#9th Way :- using np.random.rand#
#################################

h=np.random.rand(4,5)
print(h)

[[0.14033145 0.19128301 0.00628659 0.90210402 0.07744949]
 [0.7304954  0.40145157 0.11724676 0.15145662 0.44356867]
 [0.69928066 0.61290881 0.64299751 0.9848059  0.99984902]
 [0.71953127 0.20750739 0.58911245 0.21154268 0.65103409]]


In [22]:
############################
#10th Way :- using np.empty#
############################

i=np.empty((4,5))
print(i)

[[0.14033145 0.19128301 0.00628659 0.90210402 0.07744949]
 [0.7304954  0.40145157 0.11724676 0.15145662 0.44356867]
 [0.69928066 0.61290881 0.64299751 0.9848059  0.99984902]
 [0.71953127 0.20750739 0.58911245 0.21154268 0.65103409]]


In [23]:
##########################
#11th Way :- using np.eye#
##########################

j=np.eye(4,4)
print(j)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
###############################
#12th Way :- using np.identity#
###############################

k=np.identity(4,dtype=np.int16)
print(k)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [54]:
#Array Attributes#

#Ndim#
#Shape#
#Size#
#Dtype#
#Itemsize#
#Reshape#
#Head#
#Tail#

l=np.empty((5,3))
print("Empty Array =\n",l)

print()

m=np.ndim(l)
print("Ndim =",m)

n=np.shape(l)
print("Shape =",n)

o=np.size(l)
print("Size =",o)

p=l.dtype
print("Dtype =",p)

q=l.itemsize
print("Itemsize =",q)

print()

r=l.reshape(3,5)
print("Reshape Array =\n",r)

import pandas as pd

S=pd.Series(np.random.rand(10))

print()

s=S.head(2)
print("Head =\n",s)

print()

t=S.tail(2)
print("Tail =\n",t)

Empty Array =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ndim = 2
Shape = (5, 3)
Size = 15
Dtype = float64
Itemsize = 8

Reshape Array =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Head =
 0    0.002615
1    0.411762
dtype: float64

Tail =
 8    0.458269
9    0.753619
dtype: float64
